### ISSUE TITLE
Help with Postgres Linux and Windows client

### ISSUE THREAD

**Issue by FTeran13** [laurenz/laurenz.github.io#1]
Hi Laurenz,

We have a Postgres Linux server running correctly and when we use a linux postgresql tool it runs correctly. When we run a Windows postgresql tool like pgAdmin or SQL Manager we get an out of memory error. Any suggestions?

**Comment by laurenz** [comment]
Try to figure out where the error happens. Try to find what causes it and fix or avoid the problem.
